### ISSUE TITLE
Remove the number from task name

### ISSUE THREAD

**Issue by marcindata** [datacamp/projects-basic-introduction-python#1]
We should clean numbers from task titles.
It should not contain a number as a prefix.

Some of the projects do not contain the numbers:
https://www.datacamp.com/projects/12
It should be same for all.

As a reference, I have added the issue from the main app: datacamp/main-app#3507.

**Comment by rasmusab** [comment]
Ok, actually not closing this as I don't have permission, but feel free to close this @davidventuri  :)
