### ISSUE TITLE
Task 5 | Update Instructions

### ISSUE THREAD

**Issue by ramnathv** [datacamp/projects-basic-introduction-python#5]
While analyzing projects and building a dashboard, I chanced upon a very interesting insight. TLDR; The instructions for Task 5 can be ambiguous and need to be updated to increase completion rates!

@davidventuri cc @ncarchedi @martijnsublime 

__1 | Task 5 has the lowest completion rate in this project__

![image](https://user-images.githubusercontent.com/346288/38386159-a6adfc64-38c8-11e8-976e-862b749edd8b.png)

__2 | Shown below is the code from some users who did NOT complete Task 5__

![image](https://user-images.githubusercontent.com/346288/38386211-cbf51214-38c8-11e8-8a3b-b0125bd3f560.png)

__3 | The confusion occurs due to the Instructions for Task 5__

![image](https://user-images.githubusercontent.com/346288/38386256-e8db2d5a-38c8-11e8-836f-8acc64e92617.png)

**Comment by davidventuri** [comment]
I remember doing this project and also being confused by where to find the market share percentages, only to find them hidden beneath a scroll in the instructions panel. I actually Googled market share percentage.

I have made the bulleted instruction clearer: "Replace the ... in each label with the market share percentage for each smartphone company in companies."

I have also made the market share percentages immediately visible below the horizontal line in the instructions panel so no scrolling is needed.
